### PR TITLE
Adding high_speed communication with FT245_FIFO

### PR DESCRIPTION
**Pull request by RpDp-git**
The new directory added includes an ICE studio module that lets users write data from PC to FPGA at USB 2.0 speeds (330 Mbps) over a parallel interface. A sample python sketch is also included as an example to get started.

### CODE REVIEW

**Comment by jojo535275** [comment]
Thanks a lot @RpDp-git for sharing this!
I did not tested it but may use your block in the future!

Little comments: 
- If you have a 60mhz PLL icestudio block for your fpga board, you can share it too ( maybe we can put it in the icePLL collection )!
- To make it a bit clearer, In the text description of the block ( or the naming of the block), You can mention that this is a "FT245 to 8bit_parallel" reading block (Fpga point of view). And the opposite communication block, the "8bit_parallel to FT245" writing block, remains to be designed ;-) ) 

Thanks again and have a nice day!

**Comment by RpDp-git** [comment]
I'm updating the block description. I think the one you mentioned suits the code better. Yes, at some point soon I will implement the write block.

Cheers!

**Comment by jojo535275** [comment]
What fpga are you using? Ice40, ecp5,...?
Did you manage to make an exact 60Mhz clock output?
For my ECP5 board (clocked at 25mhz), i could only make  a 25mhz to 62.5 mhz pll block (that i added now to the icepll collection)
i don't know yet if it will work properly with your Ft245 block!

cheers!

**Comment by RpDp-git** [comment]
I used the clock on the ftdi board. It requires all data transfer to be
synced to that clock for synchronous fifo. I used a tinyfpga bx

**Comment by jojo535275** [comment]
ah, yes,  i see now !! My question was quite dumb ;-)
Thanks

**Pull request merged**
